#!/bin/sh
# Wyze Cam-to-Google Drive
# Uploads newly-recorded videos to Google Drive when running from a Wyze Cam with wz_mini_hacks installed; update CLIENTID, CLIENTSECRET and REFRESHTOKEN as required

CLIENTID=""
CLIENTSECRET=""
REFRESHTOKEN=""

while true
do
	touch /tmp/lastwatch
	
	# Get current epoch time
	CURRENTTIME=$(date +%s)

	# Calculate epoch time for 5 minutes from now
	FIVEMINSAHEAD=$((CURRENTTIME + 300))

	# Convert that epoch time to the format touch expects (YYYYMMDDhhmm.ss)
	FORMATTEDTIME=$(date -d "@$FIVEMINSAHEAD" +"%Y%m%d%H%M.%S")

	# Use touch to set the time
	touch -t $FORMATTEDTIME /tmp/limitwatch
	
	# Arbitrary pause so as to not continuously write to microSD card
	sleep 5
	
	# Look for newly-recorded videos on the microSD card
	find /media/mmc/record -type f -newer /tmp/lastwatch ! -newer /tmp/limitwatch -print | while read filepath; do
		YYYYMMDD=$(basename $(dirname $(dirname "$filepath")))
		HH=$(basename $(dirname "$filepath"))
		MM=$(basename "$filepath" .mp4)
		
		RESULT=$(curl -k -d "client_id=$CLIENTID&client_secret=$CLIENTSECRET&refresh_token=$REFRESHTOKEN&grant_type=refresh_token" https://accounts.google.com/o/oauth2/token)
		
		ACCESSTOKEN=$(echo "$RESULT" | grep -o '"access_token": "[^"]*"' | sed 's/"access_token": "//' | sed 's/"//')
		
		# Upload via curl
		curl -k -X POST -L \
			-H "Authorization: Bearer $ACCESSTOKEN" \
			-F "metadata={name :'${YYYYMMDD}-${HH}${MM}.mp4'};type=application/json;charset=UTF-8" \
			-F "file=@$filepath;type=video/mp4" \
			"https://www.googleapis.com/upload/drive/v3/files?uploadType=multipart"
	done
done
